services:
    Asdoria\SyliusCatalogModePlugin\EventListener\AddToCartListener:
        arguments:
            $translator: '@translator'
        calls:
            - [ 'setCatalogModeChecker', [ '@Asdoria\SyliusCatalogModePlugin\Checker\CatalogModeChecker' ] ]
        tags:
            - { name: kernel.event_listener, event: 'sylius.order_item.pre_add', method: onCheck }
